# Generated by Django 5.1.3 on 2024-11-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.driver'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bus',
            name='allowed_drivers',
        ),
        migrations.AddField(
            model_name='bus',
            name='allowed_drivers',
            field=models.ManyToManyField(blank=True, to='dispatcher.driver'),
        ),
    ]
