# Generated by Django 5.1.3 on 2024-11-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_reservation_driver_remove_bus_allowed_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_buses', to='dispatcher.driver'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='allowed_drivers',
            field=models.ManyToManyField(blank=True, related_name='allowed_buses', to='dispatcher.driver'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='ready',
            field=models.BooleanField(default=True),
        ),
    ]
